version: '3.8'

# This is a docker compose file for local development

services:
  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
  maildev:
    image: maildev/maildev
    restart: always
    ports:
      - 1080:1080
      - 1025:1025